# Generated by Django 3.1.5 on 2021-02-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210203_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='background_image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='contact_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='disabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='logo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='member_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='org',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Organization Password'),
        ),
        migrations.AlterField(
            model_name='org',
            name='restricted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='restriction_type',
            field=models.IntegerField(default=1),
        ),
    ]
