# Generated by Django 3.1.5 on 2021-02-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210203_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_owner', to=settings.AUTH_USER_MODEL, verbose_name='Organization Owner'),
        ),
    ]
