# Generated by Django 3.1.5 on 2021-02-06 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210205_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgapplication',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
