# Generated by Django 3.1.5 on 2021-02-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210206_1314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orgapplication',
            unique_together={('id', 'owner')},
        ),
    ]
