# Generated by Django 3.1.5 on 2021-02-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210206_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orgapplication',
            unique_together=set(),
        ),
    ]
