# Generated by Django 3.1.5 on 2021-02-06 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210206_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgapplication',
            name='date_accepted',
        ),
        migrations.RemoveField(
            model_name='orgapplication',
            name='decline_reason',
        ),
        migrations.RemoveField(
            model_name='orgapplication',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='orgapplication',
            name='is_accepted',
        ),
        migrations.CreateModel(
            name='OrgMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_org_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='org',
            name='members',
            field=models.ManyToManyField(to='api.OrgMembers', verbose_name='Organization Member'),
        ),
    ]
